apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-service
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/location-service
    repoURL: https://github.com/onalv/Projects.UdaConnect.git
    targetRevision: HEAD
  syncPolicy: {}